### ISSUE TITLE
[Feature]: Add a python file to update requirements.txt automatically.

### ISSUE THREAD

**Issue by PavanTeja2005** [suryanshsk/Python-Voice-Assistant-Suryanshsk#101]
Problem description: As many developers are contributing to the project it's important to update reqirements.txt to date.

Solution: To ease this up I want to create a python code which can scrape all python files and add required unadded modules to requirements.txt automatically

**Comment by wizaye** [comment]
hey @suryanshsk would like to work on this can you please assign this to me?

**Comment by wizaye** [comment]
@suryanshsk  please check the pr  #105. Let me know any comments/changes ;)
