### ISSUE TITLE
Improving "wikipedia_info.py"

### ISSUE THREAD

**Issue by Kritika75** [suryanshsk/Python-Voice-Assistant-Suryanshsk#109]
We can add following:

1. Users input their search query, specify the number of sentences for the summary, and choose the language of the Wikipedia page.
2. Search history
3. Disambiguation Handling
4. Language Support
5. Formatted Output
6. Users can choose between searching, viewing search history, or exiting the program, enhancing the user experience.
7. Error handling & logging feature

@suryanshsk can you assign me this??

**Comment by wizaye** [comment]
@suryanshsk would like to work on this could you assign this to me?

**Comment by Kritika75** [comment]
@wizaye It is already assigned to me

**Comment by Veeransh14** [comment]
@suryanshsk can I work on this issue as well if @Kritika75 doesn't mind ?
A few things which can be worked on: 
- Allowing user input via command line 
- Handling disambiguation
- Allowing specification of number of sentences in summary
- Fetching full page content
- Setting language for Wikipedia searches

**Comment by Kritika75** [comment]
Hey there, @Veeransh14 ! I just wanted to let you know that I'm already on it, and it's been assigned to me. They have the same features. Just a friendly tip: it's best not to comment on an issue opened by someone else when it's already been assigned unless that person is unassigned or leaves the issue for someone else to take.

**Comment by suryanshsk** [comment]
Thanks Kritika for doing my work 😅
