### ISSUE TITLE
add Requirements.txt file

### ISSUE THREAD

**Issue by jaidh01** [suryanshsk/Python-Voice-Assistant-Suryanshsk#13]
I recommend adding a requirements.txt file to the repository. This would allow anyone to easily install the necessary dependencies and start using the app, making it simpler for users and contributors to find bugs or suggest improvements.

Request : - Kindly assign this issue to me and label it as gssoc24-extd and hacktoberfest.

**Comment by suryanshsk** [comment]
Okay sure

**Comment by jaidh01** [comment]
Sir, can you please add the hacktoberfest-accepted label and the level label, in this issue as well.

**Comment by jaidh01** [comment]
Hi, @suryanshsk, 
I noticed that the PR for this issue was closed. Could you please provide some feedback or suggestions on what changes I should make to improve it? I’d be happy to revise and resubmit based on your guidance.

**Comment by suryanshsk** [comment]
don't worry i merged your pull request

**Comment by jaidh01** [comment]
Hi @suryanshsk , @Harsh8833, @sanjay-kv 
I request you to please add the `level` label to this issue. As without that it wasn't be count in gssoc-extd.
And I also want to inform that this repo **`doesn't have the Hacktoberfest,`** because of which it is not getting count in my Hacktoberfest.
Thank you for your time.

**Comment by suryanshsk** [comment]
Ok, I will check.
