### ISSUE TITLE
Add Google Calendar Integration

### ISSUE THREAD

**Issue by imDarshanGK** [suryanshsk/Python-Voice-Assistant-Suryanshsk#151]
I want to work on integrating Google Calendar into the voice assistant to enable features like setting reminders, scheduling events, and viewing upcoming tasks. @suryanshsk

**Comment by imDarshanGK** [comment]
Hi @suryanshsk ,

I wanted to let you know that I’ve completed this pull request for the Python Voice Assistant project. This update includes the Google Calendar integration, allowing users to view events, create new events, and set reminders. The main goal is to make the project easier for others to use and understand.

I’d be grateful for any feedback you have.

Best regards,  
@imDarshanGK  [Darshan]

**Comment by imDarshanGK** [comment]
This pull request updates the Google Calendar code to make it easy for others to use:

1} It removes my personal file path for credentials.json and uses a simpler setup.
2} Now, anyone can add their own credentials.json file without changing the code.

@suryanshsk

**Comment by suryanshsk** [comment]
Sorry, Your issue is not related with our project
