### ISSUE TITLE
add_contributor.yml adding a lot of garbage commit

### ISSUE THREAD

**Issue by jitendra-ky** [suryanshsk/Python-Voice-Assistant-Suryanshsk#153]
this add_contributor.yml github action workflow adding a lot of garbage commits.
which add a commit `update contributor list` whenever any contributor make commit.
which make commit history untidy.
![image](https://github.com/user-attachments/assets/dcf4aaf1-19e7-4c29-98de-64a7ba52c990)
![image](https://github.com/user-attachments/assets/4fd23619-0f8e-480f-81e3-841e4f5a1e4c)

> I suggest removing this workflow file

**Comment by wizaye** [comment]
@jitendra-ky Thanks for pointing out the issue, it is essential for `add_contributor.yml` to be present as we have `gssoc-ext` along side with `hacktoberfest2024` going on and it will be a valid proof for the people who are putting out code into the repo. Hope you understand this.
@suryanshsk @yashksaini-coder please look into schedule cron jobs / auto skip the update contributors commit on to the work tree.
#### Other workarounds:
- If atmost important we can route this contributor commits updation of add_contributor.yml to a seperate branch as @jitendra-ky mentioned for a clean worktree.
- Allow Squash Merging
- (Let us know if any other alternatives)

**Comment by wizaye** [comment]
@jitendra-ky @suryanshsk can you close issue as it was resolved with the pr #155
