### ISSUE TITLE
Fixing add-contributor.yml to erase garbage commits

### ISSUE THREAD

**Issue by yashksaini-coder** [suryanshsk/Python-Voice-Assistant-Suryanshsk#155]
@jitendra-ky Thanks for pointing out the issue, it is essential for `add_contributor.yml` to be present as we have `gssoc-ext` along side with `hacktoberfest2024` going on and it will be a valid proof for the people who are putting out code into the repo. Hope you understand this.
@suryanshsk @yashksaini-coder please look into schedule cron jobs / auto skip the update contributors commit on to the work tree.
#### Other workarounds:
- If atmost important we can route this contributor commits updation of add_contributor.yml to a seperate branch as @jitendra-ky mentioned for a clean worktree.
- Allow Squash Merging
- (Let us know if any other alternatives)

_Originally posted by @wizaye in https://github.com/suryanshsk/Python-Voice-Assistant-Suryanshsk/issues/153#issuecomment-2406783477_

**Comment by yashksaini-coder** [comment]
This issue highlights the garbage commits, I will add the github-bot user id in the original workflow configs @wizaye @suryanshsk

**Comment by wizaye** [comment]
@yashksaini-coder yea that will be a cleaner approach to handle the issue. Never the less checkout other possible alternatives as we have people coming into repo for contributions.

**Comment by yashksaini-coder** [comment]
@wizaye also can you assign me this issue with gssoc & hacktoberfest labels.

**Comment by wizaye** [comment]
> ```
>           @jitendra-ky Thanks for pointing out the issue, it is essential for `add_contributor.yml` to be present as we have `gssoc-ext` along side with `hacktoberfest2024` going on and it will be a valid proof for the people who are putting out code into the repo. Hope you understand this.
> ```
> 
> @suryanshsk @yashksaini-coder please look into schedule cron jobs / auto skip the update contributors commit on to the work tree.
> 
> #### Other workarounds:
> * If atmost important we can route this contributor commits updation of add_contributor.yml to a seperate branch as @jitendra-ky mentioned for a clean worktree.
> * Allow Squash Merging
> * (Let us know if any other alternatives)
> 
> _Originally posted by @wizaye in [#153 (comment)](https://github.com/suryanshsk/Python-Voice-Assistant-Suryanshsk/issues/153#issuecomment-2406783477)_

**Comment by wizaye** [comment]
@yashksaini-coder i dont have permission for that , you can ask @suryanshsk to assign the labels as he's the owner of the repo

**Comment by yashksaini-coder** [comment]
okh does the project has a channel in discord ? if don't let @suryanshsk know to make one in gssoc

**Comment by suryanshsk** [comment]
https://discord.gg/hpzJyzC2
