### ISSUE TITLE
A Memory Game

### ISSUE THREAD

**Issue by Kritika75** [suryanshsk/Python-Voice-Assistant-Suryanshsk#160]
A memory game where the assistant gives a sequence of words or numbers for the user to repeat, like it will involve difficulty levels, score tracking, hints, restart, leaderboard, save & load game and visual feedback like red for incorrect and green for correct

@suryanshsk can you assign me this?

**Comment by Kritika75** [comment]
Hey @suryanshsk can you close my these issues as I've completed them 

#160  #109  #90  #70

**Comment by suryanshsk** [comment]
Yes, it's done.
