### ISSUE TITLE
Improve README format

### ISSUE THREAD

**Issue by yashksaini-coder** [suryanshsk/Python-Voice-Assistant-Suryanshsk#17]
Hi @suryanshsk I noticed that your readme can be improved, to make it easy to interact with and also include badges to make it look more impressive.

I would like to work on this issue, assign it to me & add labels `gssoc` & `hacktoberfest` labels to it.

**Comment by suryanshsk** [comment]
Okay sure

**Comment by AnujSaha0111** [comment]
Can you please assign it to me?

**Comment by AnujSaha0111** [comment]
#39
