### ISSUE TITLE
Tic Tac Toe game

### ISSUE THREAD

**Issue by 23wh1a0513** [suryanshsk/Python-Voice-Assistant-Suryanshsk#213]
Tic Tac Toe is more than just a game; it serves as an educational tool for developing skills in logic, planning, and critical thinking. Its simplicity makes it accessible to players of all ages, while its strategic elements can offer deeper insights for those looking to sharpen their gaming skills.

**Comment by 23wh1a0513** [comment]
@suryanshsk Here is the demo


https://github.com/user-attachments/assets/070d5cba-e0d1-453a-9782-0589e70030b9

**Comment by maniranjan2023** [comment]
Kindly assign this task to me...I want to contribute

**Comment by 23wh1a0513** [comment]
@suryanshsk I have added the file.Raised pr

**Comment by ayushcodes0** [comment]
@suryanshsk assign this task to me

**Comment by Nikita-Kulshrestha** [comment]
@suryanshsk, I wish to work on this issue.. kindly assign this task to me :)

**Comment by suryanshsk** [comment]
I can't assign now because we have already assigned if you have some new creative in this then  I will assign you

**Comment by Nikita-Kulshrestha** [comment]
> I can't assign now because we have already assigned if you have some new creative in this then I will assign you

Can I try to work on the game in an individual file and send that to you? if you approve, i'll submit a pull request?

**Comment by Nikita-Kulshrestha** [comment]
hello @suryanshsk I am ready with a demo so far, I would like to show you what ive come up with till now, and if you like it, i wish to tell you about my next few ideas. 

https://github.com/user-attachments/assets/51a2b10d-3438-49bf-b9f8-158304bf3d93

**Comment by maniranjan2023** [comment]
sir, please add tag of hacktoberfest, and level

**Comment by Nikita-Kulshrestha** [comment]
Hi @suryanshsk , I noticed another contributor made a commit for the same issue—could you please review my version and let me know if I should proceed or make any changes?"
