### ISSUE TITLE
Enhancement of news_info feature 

### ISSUE THREAD

**Issue by Chin-may02** [suryanshsk/Python-Voice-Assistant-Suryanshsk#22]
1. Addition of better error handling
2. Adding categories location etc
3. Ability to retrive N number of articles as provided by the user 
 Could you please assign me this task and add the tags gssoc-ext, hacktoberfest-accepted so that I could contribute to the work.

**Comment by suryanshsk** [comment]
Your request is approved.

**Comment by Chin-may02** [comment]
Would you like me to add it as a new file or edit it in the existing one also could you please assign the level of this task

**Comment by suryanshsk** [comment]
New file

**Comment by Chin-may02** [comment]
Thanks, will do it
