### ISSUE TITLE
Enhancement: Improve the weather info feature

### ISSUE THREAD

**Issue by djv554** [suryanshsk/Python-Voice-Assistant-Suryanshsk#23]
I would like to implement the following features in the weather info code:
1) Error Handling
2) Convert Kelvin to Celsius Function
3) Environment Variables for API Key
Please assign this task to me under the labels of GSSoC-extd and Hacktoberfest.

**Comment by Herostomo** [comment]
I would like to implement these features in the weather_info code :
1. Error handling : Error Handling with try-except: The requests.get() call is wrapped in a try-except block to handle potential exceptions, such as network issues.
2. Input Validation: Before making the API request, the city name is validated to avoid sending empty or invalid requests.

3. API Key Security: The API key is now fetched securely from an environment variable (OPENWEATHER_API_KEY), which is more secure than hardcoding it into the script.

4. Improved CLI Interaction: A simple CLI interaction is provided with input() to allow users to provide the city name and preferred units.
5. Detailed Error Handling: The function now handles various error codes (404, 401, 429), providing more informative feedback for different failure scenarios.

**Comment by djv554** [comment]
Done please check it
