### ISSUE TITLE
Error in installing dependencies from requirements.txt

### ISSUE THREAD

**Issue by zsquare12** [suryanshsk/Python-Voice-Assistant-Suryanshsk#25]
I am attempting to set up the virtual environment for this Django project. After creating and activating the virtual environment, I ran the following command:

```bash
pip install -r .\requirements.txt
```

However, I encountered the following error:

```
ERROR: Could not find a version that satisfies the requirement request (from versions: none)
ERROR: No matching distribution found for request
```

It seems there may be a typo in the `requirements.txt` file.

Additionally, I would like to request the following tags be added to this issue:
- `gssoc-ext`
- `level1`
- `hacktoberfest`

**Comment by zsquare12** [comment]
@suryanshsk , assign this to me I can fix this.

**Comment by zsquare12** [comment]
@suryanshsk ,

Just a note regarding the tags: according to GSSoC, the correct tag should be **`gssoc-ext`** instead of **`GSSoC 24 Extd`**.

Thanks for your attention!

**Comment by suryanshsk** [comment]
Thank you for the clarification.
