### ISSUE TITLE
Enhancement of text to voice 

### ISSUE THREAD

**Issue by Chin-may02** [suryanshsk/Python-Voice-Assistant-Suryanshsk#28]
Choice of different voices 
Rate and volume control 
Better error handling 
Could you please assign me this task so that I can contribute with addition of labels like gssoc-ext, hacktoberfest-accepted and level and work on in by the earliest

**Comment by Chin-may02** [comment]
Do I add a new file or edit the new one

**Comment by suryanshsk** [comment]
Add a new file

**Comment by Chin-may02** [comment]
Done with both could you please check it

**Comment by suryanshsk** [comment]
Yes, it looks good. I already merged that in my project

**Comment by Chin-may02** [comment]
Thanks for the support

**Comment by suryanshsk** [comment]
Glad to hear it!
