### ISSUE TITLE
add random joke generator

### ISSUE THREAD

**Issue by kushwxha** [suryanshsk/Python-Voice-Assistant-Suryanshsk#287]
add random joke generator to the projects

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me? @suryanshsk

**Comment by JanviGundawar03** [comment]
Hi! I'd love to work on this issue. Could you please assign it to me?

**Comment by kushwxha** [comment]
hey @suryanshsk,
i am little bit confuse .there are so many file in repo in which file i have to write the code or do ihave make a new one?
