### ISSUE TITLE
Change ,yml to .yml

### ISSUE THREAD

**Issue by AnanteshG** [suryanshsk/Python-Voice-Assistant-Suryanshsk#295]
![{80E39A93-F3A8-47D9-973F-738523A85C24}](https://github.com/user-attachments/assets/647df098-ea01-4735-88f4-63fe111d5695)

In the above image, it says ,yml instead of .yml

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me? @suryanshsk
