### ISSUE TITLE
Improve the voice recognition feature

### ISSUE THREAD

**Issue by djv554** [suryanshsk/Python-Voice-Assistant-Suryanshsk#30]
Hi, 
I would like to improve the voice recognition code as follows:
1)Retry Mechanism
2)Error Handling
3)Dynamic language support
Please assign this with the gssoc-ext and hacktoberfest labels.

**Comment by suryanshsk** [comment]
Yes, you can do that.

**Comment by djv554** [comment]
Done please check it

**Comment by suryanshsk** [comment]
Looks good, thanks!
