### ISSUE TITLE
Addition of a navigation tool 

### ISSUE THREAD

**Issue by Chin-may02** [suryanshsk/Python-Voice-Assistant-Suryanshsk#31]
A navigation app which will use google maps and need an API key but would function 
This will also have a speech feature 
Provides direction from current location provide by the user to the destination

**Comment by suryanshsk** [comment]
That's awesome

**Comment by Chin-may02** [comment]
Thanks will get back to you in a while

**Comment by Chin-may02** [comment]
Could you please check it and verify whether it can qualify as a level-2

**Comment by suryanshsk** [comment]
Ok, I will check.

**Comment by Chin-may02** [comment]
Thanks do I update the pull request as well ?

**Comment by suryanshsk** [comment]
Yes, you can do that. ,
