### ISSUE TITLE
✨[FEATURE] Voice activated coding

### ISSUE THREAD

**Issue by Chin-may02** [suryanshsk/Python-Voice-Assistant-Suryanshsk#328]
## 🌟 Feature Overview
This would allow the user to write a code with voice prompts

## 🤔 Why this feature?
This is to help users understand different coding languages and assists them while working

## 📋 Expected Behavior
Voice input of expected code and output is displayed 

## 🖼️ Example/Mockups
N/A

## 📝 Additional Details
This can also guide the user while they are coding by giving them hints

**Comment by lakshaymittal45** [comment]
i want to get access to perform this task

**Comment by lakshaymittal45** [comment]
I am really excited to contribute to this project, Looking forward to contribute to this amazing project

**Comment by lakshaymittal45** [comment]
Hi can you please confirm do you only need Voice to prompt text conversion and prompt response printing? Or an Ai based response generation as well ( using API )

**Comment by suryanshsk** [comment]
I'm using Api for response generation

**Comment by lakshaymittal45** [comment]
So i need to provide you the input and output code for your generated response right?

**Comment by suryanshsk** [comment]
It's already in our project
