### ISSUE TITLE
✨[FEATURE] QR Code Generator

### ISSUE THREAD

**Issue by AnanteshG** [suryanshsk/Python-Voice-Assistant-Suryanshsk#364]
## 🌟 Feature Overview
Add All images and it generates different QRs for different QR Codes. 

## 🤔 Why this feature?
Easy QR generation with no manual work

## 📋 Expected Behavior
_What do you expect from this feature? Provide detailed information on how it should work._

## 🖼️ Example/Mockups
_If applicable, add examples or mockups that illustrate how the feature should look or behave._

## 📝 Additional Details
_Add any other details or suggestions._

**Comment by maniranjan2023** [comment]
@suryanshsk sir, i want to contribute in this issue.....please assign me this  task

**Comment by AnanteshG** [comment]
Do create your own issues if you want to contribute.
