### ISSUE TITLE
Feature Request : Add Chatbox Functionality

### ISSUE THREAD

**Issue by Shalini22-ui** [suryanshsk/Python-Voice-Assistant-Suryanshsk#369]
I propose adding a chatbox feature to our project. This feature will provide users with instant responses and support, enhancing the overall user experience.
![WhatsApp Image 2024-10-20 at 8 33 02 PM](https://github.com/user-attachments/assets/a13c89f3-8a77-43cf-821c-093fa1adb709)

**Comment by bullseye4703** [comment]
i would love to contribute int this repo please assign this to me,I can do it by tomorrow afternoon

**Comment by Shalini22-ui** [comment]
@bullseye4703 please create your own issues to contribute to this project

**Comment by JOSHITHA6** [comment]
@suryanshsk kindly assign this task to me under gssoc'24 ectd and hacktoberfest

**Comment by suryanshsk** [comment]
This is not related with Python Voice Assistant projects
