### ISSUE TITLE
✨ Add a feature to generate code and write into Vs Code

### ISSUE THREAD

**Issue by call-meRavi-SHORT-CODE** [suryanshsk/Python-Voice-Assistant-Suryanshsk#375]
Feature Overview:
Automatically generate code and insert it directly into the open VS Code window from an external interface or AI assistant.

🤔 Why this feature?
This feature would streamline coding workflows by automating repetitive tasks, reducing manual copy-pasting, and allowing developers to focus on complex tasks.

📋 Expected Behavior:
Generate code based on user input or templates.
Automatically insert the generated code into the active VS Code editor at the current cursor location.

**Comment by suryanshsk** [comment]
It's already exist
