### ISSUE TITLE
✨[FEATURE] GithubScraper:GitHub Repository Extraction Using BeautifulSoup

### ISSUE THREAD

**Issue by Niraj1608** [suryanshsk/Python-Voice-Assistant-Suryanshsk#393]
**Project Overview**
The GitHub Topic Extractor is a Python-based tool that scrapes repositories from GitHub and extracts relevant topics using Natural Language Processing (NLP). Leveraging BeautifulSoup for HTML parsing and NLP techniques such as tokenization and keyword extraction, this tool automates the identification of key topics or themes associated with GitHub repositories.

## Features

- **Scrapes GitHub repositories**: Extracts key information such as repository name, description, and associated topics.
- **Proxy support**: Handles IP rotation and proxies to avoid getting blocked during scraping.
- **Summarization Model**: Utilizes a summarization model (like BERT) to condense repository descriptions for further analysis.
- **NLP Integration**: Processes the extracted content using NLP techniques, extracting relevant keywords and insights.

**Comment by Niraj1608** [comment]
@suryanshsk assign me this issue :)

**Comment by Niraj1608** [comment]
@suryanshsk can you check my pr pls

**Comment by suryanshsk** [comment]
i have already checked
