### ISSUE TITLE
Enhancing the news file

### ISSUE THREAD

**Issue by Kritika75** [suryanshsk/Python-Voice-Assistant-Suryanshsk#42]
I can implement the following features:

- User Input for Customization, categories like technology or sports
- Search Functionality
- Pagination
- Error Handling
- Detailed Article Display

Can you assign me this @suryanshsk

**Comment by suryanshsk** [comment]
Yes, you can do that.

**Comment by Kritika75** [comment]
ok, thank you

**Comment by Kritika75** [comment]
Hey, can you close this issue now as it is resolved and change the label1 to label3 of this issue as you assigned it in the pull request

**Comment by suryanshsk** [comment]
Yes, it's done.
