### ISSUE TITLE
✨[FEATURE] QR Code shortener

### ISSUE THREAD

**Issue by 23wh1a0513** [suryanshsk/Python-Voice-Assistant-Suryanshsk#427]
## 🌟 Feature Overview
_Describe the feature or enhancement you would like to see._
Creating a QR code shortener can be a useful tool for converting long URLs into concise QR codes that people can easily scan.

## 🤔 Why this feature?
_Explain why this feature would be helpful and the problems it solves._
Creating a QR code shortener can be a useful tool for converting long URLs into concise QR codes that people can easily scan.

## 📋 Expected Behavior
_What do you expect from this feature? Provide detailed information on how it should work._

## 🖼️ Example/Mockups
_If applicable, add examples or mockups that illustrate how the feature should look or behave._

## 📝 Additional Details
_Add any other details or suggestions._

**Comment by suryanshsk** [comment]
this is voice assistant project so create issues related to it
