### ISSUE TITLE
✨[FEATURE] ContestHub (DevOps Project)

### ISSUE THREAD

**Issue by AnanteshG** [suryanshsk/Python-Voice-Assistant-Suryanshsk#436]
## 🌟 Feature Overview
ContestHub is a platform that aggregates upcoming and ongoing programming contests from multiple competitive programming websites (such as Codeforces, CodeChef, LeetCode, etc.) and presents them in a structured manner. It allows users to easily track contest schedules and filter them by platform or time, offering a streamlined experience for competitive programmers.

## 🤔 Why this feature?
- **Centralized Information**: ContestHub consolidates information from various competitive programming platforms, making it easier for users to view all contest details in one place without manually checking each platform.
- **Time-Saving**: Instead of browsing multiple websites, ContestHub allows users to find relevant contests quickly, saving time and effort.
- **Automation**: By continuously fetching and updating contest data automatically, ContestHub ensures that the information remains up to date, reducing the chances of missing important contests.
- **User Engagement**: Competitive programmers can plan their preparation better when they have an organized view of all contests, leading to better participation and engagement.

## 📋 Expected Behavior
- **Input**: 
  - The system will scrape programming contest data from various platforms and store it in JSON format.
  - Users can search and filter contests based on criteria such as platform, start time, and duration.
- **Processing**: 
  - Data will be continuously updated via scheduled scraping and stored in a GitHub repository (`ContestHub-backend`). This backend will serve as the database for the project.
  - Automation with CI/CD pipelines will ensure the data remains fresh and accurate.
- **Output**: 
  - The website will display upcoming and ongoing contests in a neat table or card format, sorted by platform or date.
  - Users will have the option to subscribe to weekly updates via email, informing them of upcoming contests based on their preferences.

## 🖼️ Example/Mockups
![image](https://github.com/user-attachments/assets/1c240ad4-868d-405c-86e8-e6e26f7c5ac6)

**Comment by suryanshsk** [comment]
This is Voice Assistant Project I don't think that it can relate with this project
