### ISSUE TITLE
✨[FEATURE]  Resume Application Tracking System(ATS) Using Google Gemini Pro Vision LIM Model

### ISSUE THREAD

**Issue by maniranjan2023** [suryanshsk/Python-Voice-Assistant-Suryanshsk#440]
🌟 Feature Overview
The feature is an Application Tracking System (ATS) powered by Google's Gemini Pro Vision Language Image Model (LIM). This system will automate the process of resume screening and candidate ranking by leveraging the multimodal capabilities of Gemini to analyze both the textual and visual elements of resumes (e.g., formats, infographics, charts) for a more comprehensive evaluation.

🤔 Why this feature?
Traditional ATS systems often miss out on visually rich resumes, which may not follow conventional formats but offer significant value. This feature addresses the challenge by combining advanced NLP and computer vision models to capture the full scope of a candidate’s qualifications and presentation style. It improves the accuracy of resume parsing, enhances candidate ranking, and ensures no relevant information is overlooked, thereby streamlining the recruitment process.

📋 Expected Behavior
Input: Recruiters upload resumes, which can be in various formats (PDF, Word, images).
Textual & Visual Parsing: Gemini Pro LIM will parse textual content, as well as analyze visual elements like charts, tables, and designs.
Candidate Matching: The ATS ranks candidates based on their relevance to the job description by evaluating both textual keywords and visual presentation effectiveness.
User Interface: Recruiters will receive ranked candidates, with detailed breakdowns of how each resume aligns with the job requirements.
Reporting & Analytics: The system will provide analytics on candidate matching and include diversity insights, qualification comparisons, and key skill matches.

🖼️ Example/Mockups
Dashboard: Displays the top 10 ranked candidates with resume previews.
Side-by-Side Comparison: Highlights the skills, experience, and visual layout analysis for each resume.
Heatmap: A visual heatmap on resumes showing which sections were most relevant based on the job description keywords.

📝 Additional Details
This ATS can be integrated with existing HR tools for seamless communication and candidate management.
It can also feature a feedback loop where recruiters can adjust ranking criteria based on specific needs, thus fine-tuning the model for better results over time.

**Comment by maniranjan2023** [comment]
@suryanshsk ,sir kindly assign me this issue, as i want to add some features like llm and gemini pro vision.

**Comment by Niraj1608** [comment]
@suryanshsk its been two weeks if is not working can you assign me this issue
