### ISSUE TITLE
Effects in Footer

### ISSUE THREAD

**Issue by 1754riya** [suryanshsk/Python-Voice-Assistant-Suryanshsk#449]
## 🌟 Feature Overview
Enhancing footer for better visuals.
![Screenshot (368)](https://github.com/user-attachments/assets/a702a4b2-7d87-49b3-ad01-ca0176cfb6fa)

## 🤔 Why this feature?
_Explain why this feature would be helpful and the problems it solves._

## 📋 Expected Behavior
_What do you expect from this feature? Provide detailed information on how it should work._

## 🖼️ Example/Mockups
_If applicable, add examples or mockups that illustrate how the feature should look or behave._

## 📝 Additional Details
_Add any other details or suggestions._

please assign me under gssoc'24 and Hacktoberfest.

**Comment by suryanshsk** [comment]
We have already an footer
