### ISSUE TITLE
✨[FEATURE] Youtube Video Downloader

### ISSUE THREAD

**Issue by AnanteshG** [suryanshsk/Python-Voice-Assistant-Suryanshsk#451]
## 🌟 Feature Overview
This project integrates with yt-dlp to allow users to download videos from YouTube. It enables downloading in various formats and resolutions, giving users flexibility in managing their video downloads.

## 🤔 Why this feature?
- Extract and download only the audio from a YouTube video.
- Download videos in various resolutions (360p, 720p, 1080p, etc.).
- Download multiple videos at once by providing a list of URLs.

**Comment by suryanshsk** [comment]
Hi, thank you for your interest in the project! Just a reminder, this repository is focused specifically on the Python Voice Assistant. Please make sure that any issues or PRs are relevant to this project's scope. Unrelated features or suggestions should be directed elsewhere. Thanks for understanding!
