### ISSUE TITLE
✨[FEATURE] Python Movie Scraper

### ISSUE THREAD

**Issue by AnanteshG** [suryanshsk/Python-Voice-Assistant-Suryanshsk#452]
## 🌟 Feature Overview
**Movie Details Scraper**: A feature that allows users to input the name of a movie and receive detailed information, including the movie's name, release year, rating, runtime, genres, director, writers, cast, and a plot summary.

## 🤔 Why this feature?
This feature would be helpful for movie enthusiasts, researchers, and developers looking for quick and easy access to detailed movie information. It solves the problem of manually searching for movie details on various platforms, which can be time-consuming and inefficient. By automating the process, users can get comprehensive information with just a simple input.

## 🖼️ Example/Mockups
**Example Output**:
Enter the movie name: Inception

Inception (2010) Rating: 8.8/10 (1,800,000 votes) Runtime: 2h 28m Release Date: July 16, 2010 Genres: Action, Adventure, Sci-Fi Director: Christopher Nolan Writers: Christopher Nolan Cast: Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page Plot Summary: A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.

**Comment by suryanshsk** [comment]
Hi, thank you for your interest in the project! Just a reminder, this repository is focused specifically on the Python Voice Assistant. Please make sure that any issues or PRs are relevant to this project's scope. Unrelated features or suggestions should be directed elsewhere. Thanks for understanding!
