### ISSUE TITLE
✨[FEATURE] Daily challenge based on Current affairs

### ISSUE THREAD

**Issue by Chin-may02** [suryanshsk/Python-Voice-Assistant-Suryanshsk#463]
## 🌟 Feature Overview
This would find any of the current affairs and ask a question based on it. This would maintain a streak and score board based on the questions answered. 

## 🤔 Why this feature?
To sharpen the user's knowledge in current affairs.

## 📋 Expected Behavior
As it already has a news info feature this feature would help utilize that knowledge.

## 🖼️ Example/Mockups
N/A

## 📝 Additional Details
To increase the codes versatility and dynamic features to be added.

**Comment by suryanshsk** [comment]
This issue is not related with Python Voice Assistant
