### ISSUE TITLE
✨[FEATURE] Random Wikipedia Article

### ISSUE THREAD

**Issue by SimranShaikh20** [suryanshsk/Python-Voice-Assistant-Suryanshsk#466]
Project Title: Random Wikipedia Article to Text File

Project Overview
The Random Wikipedia Article to Text File project aims to retrieve a random article from Wikipedia and save its content into a text file. This is a practical Python project that demonstrates the use of APIs and file handling, allowing users to explore random information from Wikipedia and store it for offline access or further analysis.

Objectives
Fetch a random Wikipedia article.
Extract the article’s content and save it to a local text file.
Provide a simple way to access random information from Wikipedia.

## 📝 Additional Details
By using this any user can save file locally and used it offline anytime and anywhere

@suryanshsk 
liked me idea then  assign me this issue i will work on it .

**Comment by Ashutoshdas-dev** [comment]
hey @SimranShaikh20 assign it to me i would like to work on it

**Comment by SimranShaikh20** [comment]
@Ashutoshdas-dev  i am contributor i am not PA for this repo !

**Comment by Ashutoshdas-dev** [comment]
hey @suryanshsk could u assign it to me

**Comment by suryanshsk** [comment]
This is not related with Python Voice Assistant Project
