### ISSUE TITLE
  Add Voice-to-Text Notepad Feature

### ISSUE THREAD

**Issue by call-meRavi-SHORT-CODE** [suryanshsk/Python-Voice-Assistant-Suryanshsk#467]
🌟 Feature Overview
Enable voice-to-text in Notepad for hands-free note-taking.

🤔 Why this feature?
Helps users take notes faster, improves accessibility, and allows multitasking.

📋 Expected Behavior

Voice Activation: Start voice input with a button or shortcut.
Accurate Transcription: Transcribe spoken words accurately with basic editing commands.
Auto-Save: Save text automatically as users speak.

**Comment by suryanshsk** [comment]
This is not related with Python Voice Assistant Project  Our Project is like a siri, Google Assistant
