### ISSUE TITLE
 Enhance UX for Toggle Theme and Scroll to Top Buttons

### ISSUE THREAD

**Issue by Shalini22-ui** [suryanshsk/Python-Voice-Assistant-Suryanshsk#468]
I would like to propose the following UI/UX improvements to enhance the user experience:

Add Title Attribute to Toggle Theme Icon:
Currently, the toggle theme icon does not provide any tooltip when hovered over. Adding a title attribute will display "Toggle Theme" when the user hovers over the icon, making it clear what the button does.

Add Title Attribute to Scroll to Top Button:
The scroll to top button located at the bottom right should also display a tooltip with the text "Scroll to Top" when hovered over. This will make its function more apparent to users.

Change Cursor to Pointer for Toggle Theme Icon:
Currently, the toggle theme icon does not change the cursor to indicate that it's clickable. Setting cursor: pointer will make it clear to users that they can click on the icon to toggle the theme.

Please assign me this issue under labels hacktoberfest-accepted, gssoc-ext and appropriate level

**Comment by suryanshsk** [comment]
This is not related with Python Voice Assistant Project
