### ISSUE TITLE
✨[FEATURE] Added task_automation file

### ISSUE THREAD

**Issue by nishant4500** [suryanshsk/Python-Voice-Assistant-Suryanshsk#469]
Email Notifications:Added functionality to send email notifications for task updates using Gmail's SMTP server.
Task Management with SQLite:Tasks can now be added, edited, deleted, completed, and searched.
Task prioritization (low, medium, high) and due dates are supported.
Database-backed task storage ensures persistent task tracking.
Appointment Scheduling:
Introduced appointment scheduling with reminders using the schedule library.
Improved Task Display: Tasks are now displayed with status (completed/not), priority, and due date for better clarity.

**Comment by suryanshsk** [comment]
This is not related with Python Voice Assistant Project
