### ISSUE TITLE
✨[FEATURE] Visualization of Linked list and Graphs 

### ISSUE THREAD

**Issue by Ananya-vastare** [suryanshsk/Python-Voice-Assistant-Suryanshsk#475]
## 🌟 Feature Overview
Linked List Visualizer
Feature: An interactive visualizer for linked lists that allows users to create, modify, and delete nodes, as well as visualize the structure dynamically.

Graph Visualizer
Feature: A tool to visualize various graph algorithms (like Dijkstra's, BFS, DFS) and their operations (adding nodes/edges, displaying paths) in a clear, animated manner.

## 🤔 Why this feature?
Linked List Visualizer
This feature provides an intuitive way for users to understand how linked lists operate. It visually demonstrates concepts like node insertion, deletion, and traversal, which are essential for learning data structures. By enabling real-time interaction, users can experiment with different scenarios, enhancing their learning experience.

Graph Visualizer
Graphs are fundamental in computer science, and understanding them is crucial for students and developers. This feature would help users visualize complex algorithms and data structures, making it easier to comprehend how different algorithms work and the relationships between nodes. This visual representation aids in debugging and improves learning outcomes.

## 📋 Expected Behavior
Linked List Visualizer
1)Node Creation: Users can input a value to create a new node at the beginning, end, or at a specific index in the linked list.
2)Node Deletion: Users can delete nodes by selecting them visually from the list.
3)Traversal Visualization: Highlight the nodes as the list is traversed, showing the flow from one node to the next.
4)Interactive Interface: Provide buttons for inserting, deleting, and traversing nodes, with corresponding animations reflecting each action.

Graph Visualizer
1)Dynamic Node/Edge Addition: Users can add nodes and edges to the graph interactively, with a clear visual representation of connections.
2)Algorithm Visualization: Users can select an algorithm (e.g., BFS, Dijkstra's) to run, with step-by-step animation illustrating how the algorithm processes the graph.
3)Path Highlighting: After running an algorithm, visually highlight the shortest path or the nodes visited during traversal.
4)User-Friendly Controls: Implement buttons and inputs for adding/removing nodes and edges, starting algorithms, and resetting the graph.

## 🖼️ Example/Mockups
Linked List Visualizer
Mockup Description: A visual interface showing a horizontal layout of linked list nodes. Each node is clickable for deletion, and an input box allows for adding nodes. Buttons for "Insert" and "Delete" are prominently displayed.
Graph Visualizer
Mockup Description: A dynamic graph representation where nodes can be added by clicking on a canvas. Lines represent edges, and after running an algorithm, animated highlights show the path or traversal order.
## 📝 Additional Details
_Add any other details or suggestions._

**Comment by Ananya-vastare** [comment]
@suryanshsk please assign this issue to me thank you

**Comment by suryanshsk** [comment]
This is not related with Python Voice Assistant Project
