### ISSUE TITLE
✨[FEATURE] Sleep Tracker 

### ISSUE THREAD

**Issue by amiya-cyber** [suryanshsk/Python-Voice-Assistant-Suryanshsk#480]
Description

The Sleep Tracker is a simple Python application that allows users to log their daily sleep duration and assess sleep quality. Users can input hours slept, and the application classifies the sleep as "Good" or "Bad" based on predefined criteria. It saves the data in a text file, enabling users to review their sleep history and monitor patterns over time.

Features

1. Log Sleep Data: Input and save daily sleep duration in hours to a text file.
2. Classify Sleep Quality: Classifies sleep as "Good Sleep" (7-9 hours) or "Bad Sleep" (other durations).
3. Display Sleep Log: Shows all logged entries with durations and quality classifications, along with average sleep duration.
4. Clear Sleep Data: Option to delete all logged sleep data.
5. User-Friendly Interface: Command-line menu for easy navigation.
6. Error Handling: Validates inputs and checks for the existence of the data file.

**Comment by amiya-cyber** [comment]
hello @suryanshsk can you increase the label i think it deserves level 3

**Comment by suryanshsk** [comment]
Actually this is not a part of our projects instead of that we assigned you and according to GSSoC Guidelines we can't give level 3
