### ISSUE TITLE
✨Body Mass Index (BMI) Calculator

### ISSUE THREAD

**Issue by amiya-cyber** [suryanshsk/Python-Voice-Assistant-Suryanshsk#482]
The BMI Calculator is a simple Python program that calculates the Body Mass Index (BMI) based on the user's weight (in kilograms) and height (in meters). It then categorizes the BMI into "Underweight," "Normal weight," "Overweight," or "Obese" according to standard BMI ranges. The program includes error handling to ensure valid input and provides a user-friendly command-line interface for easy use.

**Comment by JOSHITHA6** [comment]
Please assign this task to me @suryanshsk under gssoc extd and hacktoberfest

**Comment by suryanshsk** [comment]
This is not related with Python Voice Assistant projects
