### ISSUE TITLE
✨[FEATURE] Add a calendar managing feature

### ISSUE THREAD

**Issue by djv554** [suryanshsk/Python-Voice-Assistant-Suryanshsk#497]
## 🌟 Feature Overview
The Calendar Management feature allows users to interact with their calendar using voice commands. It enables users to create, view, and manage appointments or events by integrating with a calendar service like Google Calendar. 

## 🤔 Why this feature?
This feature allows users to interact with their calendar in a hands-free way, adding convenience and efficiency to daily scheduling tasks.

## 📋 Expected Behavior
The Calendar Management feature helps users:

- Add new events or appointments to their calendar.
- Retrieve their schedule for a specific day.
- Update or delete existing events.

## 🖼️ Example/Mockups
N/A

## 📝 Additional Details
Please assign this under the labels GSSoC-ext and Hacktoberfest

**Comment by suryanshsk** [comment]
This is not related with our Python Voice Assistant projects
