### ISSUE TITLE
✨[FEATURE] added Lucknow Map

### ISSUE THREAD

**Issue by Aasthaa10** [suryanshsk/Python-Voice-Assistant-Suryanshsk#507]
## 🌟 Feature Overview
_Describe the feature or enhancement you would like to see._
 added Lucknow Map

## 🤔 Why this feature?
_Explain why this feature would be helpful and the problems it solves._

## 📋 Expected Behavior
_What do you expect from this feature? Provide detailed information on how it should work._

## 🖼️ Example/Mockups
_If applicable, add examples or mockups that illustrate how the feature should look or behave._

## 📝 Additional Details
_Add any other details or suggestions._

**Comment by suryanshsk** [comment]
Don't use chat gpt every time to spam repo
