### ISSUE TITLE
🚀[ENHANCEMENT]: Update Recipe.py

### ISSUE THREAD

**Issue by Aasthaa10** [suryanshsk/Python-Voice-Assistant-Suryanshsk#509]
## ✨ Enhancement Overview
code with the enhanced features integrated, including command parsing, improved error handling for API fetching, and the ability to add new recipes via voice commands.

## 🚀 Proposed Changes
the code  enhances featuresincluding command parsing, improved error handling for API fetching, and the ability to add new recipes via voice commands.

**Comment by suryanshsk** [comment]
Briefly tell how this issue is related to our project

**Comment by Aasthaa10** [comment]
sure!!  in the recipe_book file i want to add some features like ability to add new recipes through voice commands ,errror handling by updating the code......so kindly assign me this issue

**Comment by Aasthaa10** [comment]
kindly assign me this issue

**Comment by suryanshsk** [comment]
sorry according to gssoc guidelines your repo is not related with our project

**Comment by Aasthaa10** [comment]
Can I know why???... I want to enhance the code .. and code enhancement is in the guidelines of code
