### ISSUE TITLE
Implement Issue Reminder Workflow🚀

### ISSUE THREAD

**Issue by amiya-cyber** [suryanshsk/Python-Voice-Assistant-Suryanshsk#517]
Description: Create a GitHub Actions workflow that sends reminders on open issues without updates. The workflow should post a comment prompting assignees to take action.

Expected Benefits:

Improved responsiveness and prioritization of tasks.
Increased overall productivity.

please assign me with level3 label @suryanshsk

**Comment by suryanshsk** [comment]
Sorry i can't assign this issue to you according to guidelines I can assigned only the issue related to our projects
