### ISSUE TITLE
Add Task Scheduling and Reminder Feature via Voice Commands

### ISSUE THREAD

**Issue by sanchitc05** [suryanshsk/Python-Voice-Assistant-Suryanshsk#52]
### **Description**:
Hello Admins,

I would like to propose the addition of a **Task Scheduling and Reminder** feature to Cognova. This feature would allow users to manage their schedules by setting tasks and reminders using voice commands. Additionally, users would be able to view and manage their daily schedules through a web-based interface.

#### Proposed Features:
1. **Task Scheduling via Voice Commands**: Users can schedule tasks or set reminders by speaking to the assistant (e.g., "Remind me to attend a meeting at 2 PM").
2. **Daily Schedule Summary**: The assistant can provide a voice-based summary of the user's tasks and reminders for the day.
3. **Web-Based UI for Task Management**: Users can view, edit, or delete their tasks and reminders through an easy-to-use web interface.
4. **Voice Notifications**: The assistant will notify the user with a voice reminder when a scheduled task is due.

#### Benefits:
- **Improves user productivity** by offering a hands-free way to manage tasks and reminders.
- Adds **versatility** to Cognova as a personal assistant, aligning to provide a more advanced and user-friendly virtual assistant experience.
- Offers both **voice-based interaction and a web-based interface**, giving users flexibility in managing their schedules.

#### Proposed Technologies:
- **Python's datetime module** to handle task and reminder scheduling.
- **SQLite** to store tasks and reminders locally.
- **Flask or Django** to build a web-based UI for task management.
- **SpeechRecognition** for processing voice commands.
- **Text-to-Speech (TTS)** for voice-based notifications and reminders.

I believe this feature will significantly enhance the assistant’s usability and appeal. I would be happy to take responsibility for developing this feature, and I request to be assigned this issue so I can contribute to the project.

Thank you for considering my proposal!

Best regards,  
Sanchit

**Comment by suryanshsk** [comment]
Your request is approved.

**Comment by sanchitc05** [comment]
@suryanshsk Done with the work. Please check out the PR and let me know if you have any doubts.
