### ISSUE TITLE
✨[FEATURE] Smart Flashcard Quiz App with Spaced Repetition

### ISSUE THREAD

**Issue by shriyadindi** [suryanshsk/Python-Voice-Assistant-Suryanshsk#533]
Description: Create a flashcard app that helps users memorize information using spaced repetition.
Features: Users can add, edit, and delete flashcards; the app then schedules flashcards based on the user’s performance.
Skills: Working with data structures, simple algorithms for scheduling (like the Leitner system), and possibly a GUI.

**Comment by suryanshsk** [comment]
sorry according to gssoc guidelines your issue is not related with our project
