### ISSUE TITLE
✨[FEATURE] Adding some more python simple Algorithms

### ISSUE THREAD

**Issue by 23wh1a0513** [suryanshsk/Python-Voice-Assistant-Suryanshsk#541]
## 🌟 Feature Overview
_Describe the feature or enhancement you would like to see._
These algorithms cover sorting, sequence generation, recursion, number theory, and searching techniques commonly used in programming.
## 🤔 Why this feature?
_Explain why this feature would be helpful and the problems it solves._
hese algorithms cover sorting, sequence generation, recursion, number theory, and searching techniques commonly used in programming.

## 📋 Expected Behavior
_What do you expect from this feature? Provide detailed information on how it should work._

## 🖼️ Example/Mockups
_If applicable, add examples or mockups that illustrate how the feature should look or behave._

## 📝 Additional Details
_Add any other details or suggestions._

**Comment by suryanshsk** [comment]
Sorry, Your issue is not related with our project
