### ISSUE TITLE
✨[FEATURE] NewsScraper with Gemini AI 

### ISSUE THREAD

**Issue by Niraj1608** [suryanshsk/Python-Voice-Assistant-Suryanshsk#547]
# News Scraper

A Python-based web scraper designed to extract news articles from various sources, analyze their sentiment, and provide summaries of the content. This project leverages Selenium for web scraping and advanced Natural Language Processing (NLP) techniques, including Gemini AI for sentiment analysis and summarization.

## Features

- **Web Scraping**: 
  - Efficiently extracts articles from Google News and other news websites.
  - Retrieves full content by following article links.

- **Sentiment Analysis**: 
  - Merges titles and content of articles for comprehensive analysis.
  - Utilizes Gemini AI for advanced sentiment analysis, providing accurate sentiment scores (positive, negative, neutral).

- **Summarization**:
  - Employs Gemini AI to generate concise summaries of the articles, helping users quickly grasp the main points.

- **Data Storage**: 
  - Organizes and saves extracted data in structured formats, such as CSV or JSON.

**Comment by Niraj1608** [comment]
@suryanshsk can you assign me this issue :)

**Comment by suryanshsk** [comment]
Sorry , Your issue is not related with our project
