### ISSUE TITLE
Improving "Joke" section

### ISSUE THREAD

**Issue by Kritika75** [suryanshsk/Python-Voice-Assistant-Suryanshsk#6]
Hey, I'm Kritika, a contributor from GSSOC'24. I would like to contribute to your project by enhancing the joke section. I will add the following features:

1. Category selection
2. Option to repeat or get a new joke
3. Saving favorite jokes

Please assign this issue to me with appropriate labels.

**Comment by suryanshsk** [comment]
Hi Kritika,

Thank you for your interest in contributing to the project! Your idea to enhance the joke section with category selection, repeat/new joke options, and a feature to save favorite jokes sounds fantastic and would add great functionality.

I've assigned the issue to you and added the appropriate GSSoC labels. Please feel free to proceed, and don’t hesitate to reach out if you need any assistance along the way.

Looking forward to your contribution!

Best regards,
Avanish Singh
Project Admin, GSSoC

**Comment by Kritika75** [comment]
Thank you so much, I'll start working on it.
