### ISSUE TITLE
Enhance website search feature, adding custom website searching feature.

### ISSUE THREAD

**Issue by PavanTeja2005** [suryanshsk/Python-Voice-Assistant-Suryanshsk#68]
I have found that website opening feature has limitations. It can only open certain number of  websites in it's database. 
It cannot open a custom website. i want to add that feature.

*Challenges*: Giving a custom website's exact link using speech is not possible.

*Intituions*: Based on key words search for the relavant website online and asking user to select a website from the options, or simply opening first website got on search.

**Comment by MVarun5** [comment]
can you provide me with labels cause i want to work on this project.
