### ISSUE TITLE
Main Assistant: Key Issues 

### ISSUE THREAD

**Issue by Deeptig9138** [suryanshsk/Python-Voice-Assistant-Suryanshsk#7]
Error Handling: No try-except blocks for failed speech recognition or API errors.
Unnecessary Prints: Use logging instead of print() for better debugging.
Blocking in Main Loop: Speech recognition might hang without a timeout.
Hard-Coded Media Control: Browser-based media control isn't always reliable; consider local media control.
Duplicate Conditions: 'exit' and 'stop' can be combined to reduce redundancy.
Lack of Fallbacks: No user-friendly errors for failed commands like weather or search.

Please assign this to me @suryanshsk

**Comment by suryanshsk** [comment]
Done
