### ISSUE TITLE
Updating weather_info with New Features

### ISSUE THREAD

**Issue by Kritika75** [suryanshsk/Python-Voice-Assistant-Suryanshsk#70]
1. Get a 5-day weather forecast for a specific city.
2. Display any weather alerts for the specified city.
3. Allow users to choose between metric, imperial, and Kelvin units for temperature display.
4. Improve error handling to give clear guidance for invalid inputs and API responses.
5. Save favourite cities using a JSON file for easy access to weather information.
6. Introduce logging to track API calls and errors for debugging and monitoring.

Can you assign me this? @suryanshsk

**Comment by suryanshsk** [comment]
Yes, I will do it.

**Comment by Kritika75** [comment]
thank you :)
