### ISSUE TITLE
navbar issue

### ISSUE THREAD

**Issue by ganjivamshiii** [suryanshsk/Python-Voice-Assistant-Suryanshsk#74]
I think your website doesn't have fixed navbar . I think it is good to have fixed position navbar, while scrolling page it is helpful jump one section to another.

**Comment by Hafsa-shoaib989** [comment]
@suryanshsk can you please assign this task to me?..as its been 3 weeks, which is why i am asking !

Thankyou.

**Comment by ganjivamshiii** [comment]
This issue is solved long ago , you can look for new issue.

**Comment by suryanshsk** [comment]
> This issue is solved long ago , you can look for new issue.

Yeah Exactly @Hafsa-shoaib989 Its Already Solved
